Feature1
m05e5/budget_app pull request #1
Opened 2021-12-01 07:52 UTC by m05e5

2021-12-03 20:55 UTC, Dipeshtwis reviewed
# Status: Invalid ❌

While you have done a great job in the project I cannot proceed with the code review. Please fix the issue mentioned below and then request for code review

## Reason

- [ ] Pull Requests should have a meaningful title and short summary.

### Please make sure to submit a code review when you are done with the changes that were requested

**Don't worry you still have same number of requests left as previous.**


Cheers and Happy Coding :clap: :clap: :clap: 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

**_Dipesh Kumar_**

2021-12-03 23:34 UTC, m05e5 commented
Oh yeah sorry I forgot

2021-12-04 12:26 UTC, Dipeshtwis requested changes
Hi @m05e5, 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: The application is working fine. Well done.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️

**_Check the comments under the review_**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- N.A.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-04 12:26 UTC, Dipeshtwis commented on README.md
> +
- [x] Here you should give appropriate credit to [Gregoire Vella on Behance](https://www.behance.net/gregoirevella) the [author of the original design](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=), as required by the [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/).

2021-12-04 12:26 UTC, Dipeshtwis commented on app/assets/stylesheets/application.css
> +  align-items: center; */
- [x] I would recommend removing the commented code to make the codebase cleaner.

2021-12-04 12:26 UTC, Dipeshtwis commented on app/assets/stylesheets/entities.scss
> +  // overflow: scroll;
- [x] Here as well, I would recommend removing the commented code to make the codebase cleaner.

2021-12-04 12:26 UTC, Dipeshtwis commented on app/assets/stylesheets/entities.scss
> +/* The Modal (background) */
- [x] Here as well. I would recommend removing the commented code to make the codebase cleaner.

2021-12-04 12:26 UTC, Dipeshtwis commented on app/controllers/entities_controller.rb
> +    # @category = Category.find(params[:cat])
- [x] Here as well. I would recommend removing all the commented code to make the codebase cleaner.

2021-12-04 12:26 UTC, Dipeshtwis commented on app/assets/stylesheets/categories.scss
> +  font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
- [ ] As per the requirement, the font family should be `Proxima Nova Bold` or `Proxima Nova Light`. Please update to follow the font face requirement.

2021-12-04 12:26 UTC, Dipeshtwis commented on app/views/entities/new.html.erb
> +          <%# <%= form.collection_select :cat, @categories ,:id , :name %>
- [ ] Here as well. I would recommend removing all the commented code to make the codebase cleaner.

2021-12-04 12:26 UTC, Dipeshtwis commented on app/models/category_with_entity.rb
> +    # cat.save
- [ ] Here as well. I would recommend removing the commented code to make the codebase cleaner.

2021-12-04 12:26 UTC, Dipeshtwis commented on README.md
> +[MIT](./LICENSE)
- [ ] The Licence link is broken. Please fix that to make the README professional.

2021-12-04 12:26 UTC, Dipeshtwis commented on app/views/devise/sessions/new.html.erb
> +    <% end %>
- [ ] I would recommend to follow the design and color same as given [here](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=).

### Your design

![Screenshot from 2021-12-04 17-48-26](https://user-images.githubusercontent.com/22434660/144709166-31d40cb3-5e10-423c-8851-6a7fd4a96683.png)

### GIven design 

![Screenshot from 2021-12-04 17-51-38](https://user-images.githubusercontent.com/22434660/144709219-b1b983bc-26af-48d7-b68c-9483768aa0c5.png)

2021-12-04 12:26 UTC, Dipeshtwis commented on app/views/devise/registrations/new.html.erb
> +
- [ ] Same with registration page. Please follow the [given design](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=). The input field is different and that's okay but keep design same.

### Your design

![Screenshot from 2021-12-04 17-54-25](https://user-images.githubusercontent.com/22434660/144709275-2f219de9-b3b3-450f-a705-1392e022da24.png)



### Given design

![Screenshot from 2021-12-04 17-51-11](https://user-images.githubusercontent.com/22434660/144709261-eb7abad3-d37c-4420-a906-32e57d694ab2.png)

2021-12-04 17:07 UTC, Emmyn5600 approved these changes
Hello,   @m05e5 👋🏾 👋🏾 congratulations on making it all the project requirements.

Highlights:

- Database is well structured 
- Your project is running successfully
- All tests are passing successfully.

## Optional suggestions

- N/a

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

2021-12-04 17:18 UTC, merged